import type { NextPage } from "next";
import Head from "next/head";
import Landing from "../components/Landing";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center justify-center max-w-6xl mx-auto h-screen">
      <Head>
        <title>Civan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing></Landing>
    </div>
  );
};

export default Home;
